title: ff66ccff
subtitle: ''
description: ''
author: ff66ccff
language: zh-CN
timezone: Asia/Shanghai
url: https://ff66ccff.github.io
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
source_dir: source
public_dir: public
new_post_name: ':title.md'
post_asset_folder: false
render_drafts: false
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
theme: volantis
theme_config:
  navbar:
    menu:
      - name: 博客
        icon: fa-solid fa-rss
        url: /
      - name: 分类
        icon: fa-solid fa-folder-open
        url: categories/
      - name: 归档
        icon: fa-solid fa-archive
        url: archives/
  cover:
    display:
      home: true
      archive: true
      others: false
    title: ff66ccff
    subtitle: <span id="hitokoto">加载中...</span>
    background: /photos/wallhaven-yq5ejd_3840x2400.png
    features:
      - name: 博客
        icon: fa-solid fa-rss
        url: /
      - name: GitHub
        icon: fa-brands fa-github
        url: https://github.com/ff66ccff
  sidebar:
    widget_library:
      blogger:
        avatar: /avatar.jpg
        url: /
        title: ff66ccff
  plugins:
    fancybox:
      enable: true
      js: >-
        https://cdnjs.cloudflare.com/ajax/libs/fancyapps-ui/5.0.33/fancybox/fancybox.umd.min.js
      css: >-
        https://cdnjs.cloudflare.com/ajax/libs/fancyapps-ui/5.0.33/fancybox/fancybox.css
    jquery:
      enable: true
      js: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js
  comments:
    title: <i class='fa-solid fa-comments'></i> 评论
    service: giscus
    giscus:
      repo: ff66ccff/ff66ccff.github.io
      repo-id: R_kgDOQRU2HQ
      category: Announcements
      category-id: DIC_kwDOQRU2Hc4C0foj
      mapping: pathname
      strict: '0'
      reactions-enabled: '1'
      emit-metadata: '0'
      input-position: bottom
      theme: preferred_color_scheme
      lang: zh-CN
  cdn_system:
    priority:
      - custom
      - local
      - cdnjs
      - npm
      - static
    system_config:
      custom:
        jquery: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js
        fancybox_js: >-
          https://cdnjs.cloudflare.com/ajax/libs/fancyapps-ui/5.0.33/fancybox/fancybox.umd.min.js
        fancybox_css: >-
          https://cdnjs.cloudflare.com/ajax/libs/fancyapps-ui/5.0.33/fancybox/fancybox.css
import:
  head_end:
    - <link rel="stylesheet" href="/css/custom.css">
  body_end:
    - <script src="/js/custom.js"></script>
skip_render:
  - hitokoto/sentences.md
